spring:
  datasource:
    platform: mysql
    gplace:
      jdbc-url: 
      username: 
      password: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      testOnBorrow: true
      validationQuery: SELECT 1
      continue-on-error: true
      hikari:
      maximum-pool-size: 1
